version: "3"
services:
  database-nosql:
    image: mongo:3.6.13
    volumes:
      - ./mongodb:/data/db
    command: mongod --smallfiles --bind_ip=0.0.0.0 --logpath=/dev/null
    expose:
      - 27017
  
  admin-mongo:
    image: mrvautin/adminmongo
    links:
     - database-nosql
    tty: true
    ports:
     - "127.0.0.1:1234:1234"
    environment:
     - CONN_NAME=zenbot_mongodb
     - DB_HOST=database-nosql
     - DB_PORT=${MONGODB_PORT}
     - HOST=0.0.0.0
    command: "npm start"

  adaptor:
    image: redis:5.0.5-alpine
    ports:
      - "6380:6380"

  loadbalancer:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - app
    ports:
      - 8082:8082
  
  app:
    build:
      context: ./app
    restart: always
    tty: true
    links:
      - database-nosql
    environment:
     - "NODE_ENV=${NODE_ENV}"
     - "SERVER_PORT=${SERVER_PORT}"
    # auth
     - "AUTH_ATTRIBUTES=${AUTH_ATTRIBUTES}"
     - "HASH_ALGORITHM=${HASH_ALGORITHM}"
     - "EXPIRES_IN=${EXPIRES_IN}"
    # redis
     - "ADAPTOR_HOST=adaptor"
     - "ADAPTOR_PORT=${ADAPTOR_PORT}"
    # mongodb
     - "MONGODB_HOST=mongodb://database-nosql:${MONGODB_PORT}/FakebookMessenger"
     - "MONGODB_RECONNECT_INTERVAL=${MONGODB_RECONNECT_INTERVAL}"
     - "MONGODB_POOL_SIZE=${MONGODB_POOL_SIZE}"
     - "MONGODB_WRITE_CONCERN_W=${MONGODB_WRITE_CONCERN_W}"
     - "MONGODB_WRITE_CONCERN_J=${MONGODB_WRITE_CONCERN_J}"
     - "MONGODB_WRITE_CONCERN_WTIMEOUT=${MONGODB_WRITE_CONCERN_WTIMEOUT}"
